config/routes.rb
Rails.application.routes.draw do
  root('static#home')
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#logout'

  get '/auth/google_oauth2/callback', to: 'sessions#omniauth'

  get '/photos/most_commented', to: 'photos#most_commented'

  resources :users
  resources :photos do
    resources :comments, only: [:new, :create, :index]

  end
  
# custom route that goes to /photos/most_commented 
#have a scope method that will organize 
#the photo by the one that has the most comments to use active record scope method 
  
  
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
  belongs_to :user
  validates :content, presence: true

  

 
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
  has_many :users, through: :comments
  has_one_attached :image
  

  validates :title, presence: true

 
  scope :desc_order, -> {order(created_at: :desc)}

  scope :most_commented, -> {joins(:comments).order( self.calculate(:count, :id))}



  
 
  
end

app/models/user.rb
class User < ApplicationRecord
    has_many :photos
    has_many :comments
    has_many :commented_photos, through: :comments, source: :photo
    has_secure_password
    has_one_attached :avatar
    

    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true 

    validates :username, presence: true
    scope :search, -> (params){where("LOWER(username)= ?", params)}

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    include ApplicationHelper

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :find_photo, only: [:index, :show, :new, :edit, :update, :create]
    

    def create  

        @photo = Photo.find(params[:photo_id])
        @comment = @photo.comments.build(params[:comment].permit(:content, :photo_id, :user_id ))
         @comment.save 
      
        flash[:message] = "yay! you just commented"
        redirect_to photo_path(@photo)
       
    end

    def index
        
        @comments = @photo.comments
    
    end

    def show 

    end
    def new
        @comment = Comment.new
    end

   

    
   
  

    private



    def find_photo
       
        @photo = Photo.find(params[:photo_id])
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
    before_action :redirect_if_not_logged_in, only: [:new, :show, :edit, :update, :create, :destroy]
    before_action :find_photo, only: [:show, :edit, :update, :create, :destroy]
 

    def new
        @photo = Photo.new 
    end


    def index
       
        @photos = current_user.photos.desc_order
        
        
        @commented_photos = current_user.commented_photos
    
    end

    
    
    

    def create
       
        
        @photo = current_user.photos.build(photo_params)
        @photo.save


        if @photo.valid?
            flash[:message] = "Photo Added Sucessfully!"
        
            redirect_to photo_path(@photo)
            
        else
            flash[:message] = "There was an Error please try again "
            render :new
        end
    end

    def show 
       
    end

    def edit 
       
    end



    def update 
       
        @photo.update(photo_params)
        if @photo.save 
            redirect_to photo_path(@photo)
        else
            render :edit
        end
    end

    

    def destroy
     
        @photo.destroy 
        flash[:message]= "Photo deleted"
        redirect_to photos_path 

    end

    def most_commented 

        @photos =  Photo.most_commented.uniq

    end


    private

    def photo_params
        params.require(:photo).permit(:title, :image)
    end

    def find_photo
        @photo = Photo.find_by(id: params[:id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end
    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            flash[:message]= "succesful sign in"
            session[:user_id] = @user.id
            redirect_to photos_path
        else
            render :new
        end
    end

    def logout
        session.clear
        redirect_to root_path
    end

    def omniauth
        @user = User.find_or_create_by(username: auth[:info][:email]) do |u|
            u.email = auth[:info][:email]
            u.username = auth[:info][:email]
            u.username = auth[:info][:name]
            u.uid = auth[:uid]
            u.provider = auth[:provider]
            u.password = SecureRandom.hex(10)
        end
        
        if @user.valid?
            session[:user_id] = @user.id
            redirect_to photos_path
        else
            flash[:message] = "Credential error"
            redirect_to login_path
        end
    end

    private
    def auth
        request.env['omniauth.auth']
    end


end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    

    def new
        @user = User.new

    end

    def create
        
        @user = User.new(user_params)
        if @user.save
            flash[:message] = "Succesfully signed up"
            session[:user_id] = @user.id
            redirect_to photos_path
        else 

            render :new
        end

      


    end
    
    def index

        @users = User.all
        if params[:q] && !params[:q].empty?
            @users = @users.search(params[:q].downcase)
        end
      
    end

   

    

    def user_params
        params.require(:user).permit(:username, :email, :password, :avatar)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

   

    def current_user
        @current_user ||= User.find_by_id(session["user_id"])
    end

    def logged_in?
        !!current_user
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    end

    def redirect_if_logged_in
        rredirect_to  root_path if logged_in?
    end

    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for([@photo,@photo.comments.build]) do |f| %>
<p>
<%= f.label :content %>
<%= f.text_area :content %>
<%= f.hidden_field :user_id, value: current_user.id %>
</p> <br>
<%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<section class="container-fluid bg1">

<% @comments.each do  |comment|  %>
<%= comment.content %> <br>

<% end %>

</section>

app/views/comments/new.html.erb
<section class="container-fluid bg6">


<h1>Leave a comment on this photo Title</h1>
<%= @photo.title %>

<%= render partial: 'form', locals: {model: @comment} %>

</section>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    
     <a <%= link_to 'MyPhotos',root_path, class: 'navbar-brand' %></a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">

      <% if logged_in? %>

        <li class="nav-item">
                <%= link_to 'View others Photos ',users_path, class: 'nav-link' %>
            </li>

      <li class="nav-item">
                <%= link_to 'Profile',photos_path, class: 'nav-link' %>
            </li>




        <li class="nav-item">
        <%= link_to 'LogOut',logout_path, method: :delete, class: 'nav-link' %>
        </li>
          
        <% else %>
            <li class="nav-item">
            <%= link_to 'Signup',signup_path, class: 'nav-link' %>
                
                </li>
                <li class="nav-item">
                <%= link_to 'Login',login_path, class: 'nav-link' %>
            </li>
        
        <% end %>



        
       
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myphotos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

   <%= render 'layouts/navbar'%>
   

     <%= flash[:message] %>
    <%= yield %>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>  
    
  </body>
</html>

app/views/photos/edit.html.erb
<section class="container-fluid bg5">

<div class="add-box">


<%= form_for(@photo)do |f| %>
  

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :image %>
<%= f.file_field :image %>

<%= f.submit 'Edit Photo' %>
<% end %>

</div>

</section>

app/views/photos/index.html.erb
<section class="container-fluid bg3">



<h2>Welcome! 
    <% if current_user.avatar.attached? %>
          <%= image_tag(current_user.avatar, style: "width: 100px; display: block" ) %>
        <% end %>
        
         <%= current_user.username %></h2><br>

<%= link_to 'Add a Photo', new_photo_path, class: 'nav-link' %> <br>


<h3> All Photos </h3>


    <% @photos.each do |photo|  %>

    <% if photo.image.attached? %>
     <%= link_to image_tag(photo.image, style: "width: 200px; display: block" ), photo_path(photo)%> <br>
    <% end %> 

<% end  %><br>




<h2>below view commented photos</h2>
<% @commented_photos.each do |photo| %> <br>
<%= link_to photo.title, photo_path(photo) %>
<% end %> <br>




<h3><%= link_to 'view most_Commented photos', photos_most_commented_path, class: 'nav-link' %></h3> <br>
</section>

app/views/photos/most_commented.html.erb
<h1>most_Commented photos</h1>


<% @photos.each do  |photo| %>
<% if photo.image.attached? %>
     <%= link_to image_tag(photo.image, style: "width: 200px; display: block" ), photo_path(photo)%> <br>

- has  <%= photo.comments.count %> comments<br> 
<% end %><br>
<% end  %><br>

app/views/photos/new.html.erb
<section class="container-fluid bg5">

<div class="add-box">



<%= render partial: 'errors/errors', locals: {model: @photo} %>

<%= form_for(@photo)do |f| %>
  

<%= f.label :title %>
<%= f.text_field :title %>



<%= f.label :image %>
<%= f.file_field :image %>


<%= f.submit 'Submit Photo' %>
<% end %>


</div>

</section>

app/views/photos/show.html.erb
<section class="container-fluid bg2">

<div class="add-box1">



<h1>Photo</h1> <br>

<h2><%= @photo.title %></h2> <br>

<% if @photo.image.attached? %>
<%= image_tag(@photo.image, style: "width: 200px; display: block" )%>
<% end %>


<% if @photo.user_id == current_user.id%>
<%= link_to 'Edit a Photo', edit_photo_path, class: 'nav-link' %><br>


<%= button_to 'Delete Photo', photo_path, class: 'nav-link', method: :delete%> <br>

<%end%>





<h2><%= @photo.comments.count %> Comments</h2> <br>

<%= link_to 'Add a new Comment', new_photo_comment_path(@photo) %> <br><br>

<% @photo.comments.each do |comment| %>
<%= comment.user.username.capitalize %> - <%=comment.content %> <br>

<% end %> <br>   



 
<%= link_to 'View all comments ', photo_comments_path(@photo) %> <br> <br>



</div>

</section>

app/views/users/index.html.erb
<%= form_tag("/users", method: "get") do %>
 <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>


<section class="container-fluid bg7">


  <% @users.each do |user| %>
 <%= user.username%> -
    <% if user.avatar.attached? %>
          <%= image_tag(user.avatar, style: "width: 100px; display: block" ) %>
        <% end %><br> <br>

       <% user.photos.each do |photo|%>
       <%= link_to photo.title, photo_path(photo)%> <br> 
       <% if photo.image.attached? %>
          <%= link_to image_tag(photo.image, style: "width: 200px; display: block" ), photo_path(photo)%> <br>
        <% end %> 
        
        <% end %>
    <% end %>

</section>

app/views/users/new.html.erb
<section class="container-fluid bg4">

<div class="add-box">
 


<h1>Sign Up </h1>
<%= render partial: 'errors/errors', locals: {model: @user } if @user %>

<%= form_for(@user, url: "/signup")  do |f| %>

    <%= f.label :avatar %>
    <%= f.file_field :avatar %><br>

    <%= f.label :username %>
    <%= f.text_field :username %><br>

    <%= f.label :email %>
    <%= f.email_field :email, required:true %><br>

    <%= f.label :password %>
    <%= f.password_field :password %><br>



    <%= f.submit "Submit" %>
<% end  %>

      </div>

</section>